### ISSUE TITLE
linux battery status is probably collected improperly

### ISSUE THREAD

**Issue by johnnychen94** [IanButterworth/PowerMonitor.jl#1]
I don't have access to a Linux laptop, here's what I've asked to get from my friend's Ubuntu 20.04LTS. It seems like the current way is not applicable to some of the laptops; unsure of it, probably because their drivers aren't properly installed.

![image](https://user-images.githubusercontent.com/8684355/96329130-a0851f00-107c-11eb-9ab3-a52eae63f36e.png)

**Comment by IanButterworth** [comment]
Does this system have a battery?

If so, it might just be the wrong battery address. It might be necessary for this tool to run `upower -e` and somehow figure out which is the relevant object once at init, then store that for future calls.

**Comment by johnnychen94** [comment]
I'll try to borrow his laptop next week and come fix this :P

**Comment by IanButterworth** [comment]
Should be fixed since the move to `battery_cli_jll`
